// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordClique_DataAccess.Context;

#nullable disable

namespace RecordClique_DataAccess.Migrations
{
    [DbContext(typeof(RecordCliqueContext))]
    [Migration("20240729203719_update-album-profile1")]
    partial class updatealbumprofile1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecordClique.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FK_RecordLabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("FK_RecordLabelId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("RecordClique.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("RecordClique.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RecordClique.Models.RecordLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecordLabels");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.AlbumArtistLink", b =>
                {
                    b.Property<Guid>("FK_AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FK_AlbumId", "FK_ArtistId");

                    b.HasIndex("FK_ArtistId");

                    b.ToTable("AlbumArtistLinks");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.AlbumGenreLink", b =>
                {
                    b.Property<Guid>("FK_AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FK_AlbumId", "FK_GenreId");

                    b.HasIndex("FK_GenreId");

                    b.ToTable("AlbumGenreLinks");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfirmedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MoneyBalance")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserAlbumLink", b =>
                {
                    b.Property<Guid>("FK_AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FK_UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsListening")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnWishlist")
                        .HasColumnType("bit");

                    b.HasKey("FK_AlbumId", "FK_UserId");

                    b.HasIndex("FK_UserId");

                    b.ToTable("UserAlbumLinks");
                });

            modelBuilder.Entity("RecordClique.Models.Album", b =>
                {
                    b.HasOne("RecordClique.Models.RecordLabel", "RecordLabel")
                        .WithMany("Albums")
                        .HasForeignKey("FK_RecordLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordLabel");
                });

            modelBuilder.Entity("RecordClique.Models.Comment", b =>
                {
                    b.HasOne("RecordClique.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordClique_DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.AlbumArtistLink", b =>
                {
                    b.HasOne("RecordClique.Models.Album", "Album")
                        .WithMany("AlbumArtistLinks")
                        .HasForeignKey("FK_AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordClique.Models.Artist", "Artist")
                        .WithMany("AlbumArtistLinks")
                        .HasForeignKey("FK_ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.AlbumGenreLink", b =>
                {
                    b.HasOne("RecordClique.Models.Album", "Album")
                        .WithMany("AlbumGenreLinks")
                        .HasForeignKey("FK_AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordClique_DataAccess.Entities.Genre", "Genre")
                        .WithMany("AlbumGenreLinks")
                        .HasForeignKey("FK_GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("UserAlbumLink", b =>
                {
                    b.HasOne("RecordClique.Models.Album", "Album")
                        .WithMany("UserAlbumLinks")
                        .HasForeignKey("FK_AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecordClique_DataAccess.Entities.User", "User")
                        .WithMany("UserAlbumLinks")
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecordClique.Models.Album", b =>
                {
                    b.Navigation("AlbumArtistLinks");

                    b.Navigation("AlbumGenreLinks");

                    b.Navigation("UserAlbumLinks");
                });

            modelBuilder.Entity("RecordClique.Models.Artist", b =>
                {
                    b.Navigation("AlbumArtistLinks");
                });

            modelBuilder.Entity("RecordClique.Models.RecordLabel", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.Genre", b =>
                {
                    b.Navigation("AlbumGenreLinks");
                });

            modelBuilder.Entity("RecordClique_DataAccess.Entities.User", b =>
                {
                    b.Navigation("UserAlbumLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
